from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
group   = []

group = DefineGroup('LIBADT', src, depend = ['RT_USING_ADT_PFRDLOCK'], CPPPATH = CPPPATH)
Return('group')
