Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['UTEST_TRACING_TC']) and GetDepend(['TRACING_KSYMTBL']):
    src += ['tracing_ksymtbl_tc.c']
if GetDepend(['UTEST_TRACING_TC']) and GetDepend(['TRACING_FTRACE']):
    src += ['ftrace_tc.c', 'ftrace_function_tc.c']

group = DefineGroup('utestcases', src, depend = ['RT_USING_UTESTCASES'], CPPPATH = CPPPATH)

Return('group')
